### PR TITLE
Fix errors reported under Typescript 2.2.1

### LINKED ISSUE #285: Compile errors using Typescript 2.2.1
Installed the latest typescript build (2.2.1) and tried building antlr4ts w/ `npm install`.   During the **tsc** step it generated errors that seem reasonably related to the new features in TypeScript 2.2.    I'll dig into them.

Result:
```
src/Parser.ts(81,59): error TS2344: Type 'string' does not satisfy the constraint 'object'.
src/Parser.ts(810,4): error TS2322: Type 'RuleContext | undefined' is not assignable to type 'RuleContext'.
  Type 'undefined' is not assignable to type 'RuleContext'.
src/dfa/DFAState.ts(173,56): error TS2345: Argument of type 'DFAState | undefined' is not assignable to parameter of type 'DFAState'.
  Type 'undefined' is not assignable to type 'DFAState'.
src/dfa/DFAState.ts(179,53): error TS2345: Argument of type 'DFAState | undefined' is not assignable to parameter of type 'DFAState'.
  Type 'undefined' is not assignable to type 'DFAState'.
```

### PR DESCRIPTION
**Pull request by BurtHarris**
Workaround several minor error messages introduced when switching to the Typescript 2.2.1 transpiler.   Fixes #285

I'm not sure why my name & sigil are showing up twice in the commits...

### CODE REVIEW

File: src/dfa/DFAState.ts [hunk 1]
```diff
@@ -170,13 +170,13 @@ export class DFAState {
 		if (map.has(-1)) {
 			if (map.size === 1) {
 				let result = new Map<number, DFAState>();
-				result.set(PredictionContext.EMPTY_FULL_STATE_KEY, map.get(-1));
+				result.set(PredictionContext.EMPTY_FULL_STATE_KEY, map.get(-1) as DFAState);
```
Comment (sharwell) [inline src/dfa/DFAState.ts]: :bulb: The following equivalent change would not require the type assertion:

```ts
getContextEdgeMap(): Map<number, DFAState> {
	let map = new Map<number, DFAState>(this.contextEdges);
	let existing = map.get(-1);
	if (existing !== undefined) {
		if (map.size === 1) {
			let result = new Map<number, DFAState>();
			result.set(PredictionContext.EMPTY_FULL_STATE_KEY, existing);
			return result;
		}
		else {
			map.delete(-1);
			map.set(PredictionContext.EMPTY_FULL_STATE_KEY, existing);
		}
	}

	return map;
}
```

File: src/Parser.ts [hunk 2]
```diff
@@ -807,7 +807,7 @@ export abstract class Parser extends Recognizer<Token, ParserATNSimulator> {
 			let ruleIndex: number = p.ruleIndex;
 			if (ruleIndex < 0) stack.push("n/a");
 			else stack.push(ruleNames[ruleIndex]);
-			p = p._parent;
+			p = p._parent as RuleContext;
```
Comment (sharwell) [inline src/Parser.ts]: 💭 Maybe we should check with the TypeScript project about what they expect this code to look like with TypeScript 2.2.

Comment (sharwell) [inline src/Parser.ts]: ➡️ The issue is the use of a non-`undefined` default argument overrides the type annotation, so the compiler has assumed that `p` cannot be `undefined`. The solution here (a workaround assuming that this is a bug in the compiler) is assigning `p` to a local variable at the beginning of the method, and operating on the local variable instead of `p` itself.

Comment (BurtHarris) [inline src/Parser.ts]: Yes, I tried a local variable and that worked without problem too.   I liked this version because it touched less lines of code.

I'm trying to put together an isolated repro case to file a bug with the TypeScript team.

Comment (sharwell) [inline src/Parser.ts]: > Yes, I tried a local variable and that worked without problem too. I liked this version because it touched less lines of code.

The form used here is incorrect. You assert that `p._parent` is a `RuleContext` (not `undefined`), but if that is always the case then the code is an infinite loop.

> I'm trying to put together an isolated repro case to file a bug with the TypeScript team.

Here is a self-contained reproducer:

```ts
var obj: Context = {
  parent: undefined
};

function working(p: Context | undefined) {
  while (p != null) {
    p = p.parent;
  }
}

function broken(p: Context | undefined = obj) {
  while (p != null) {
    p = p.parent;
  }
}

interface Context { parent: Context | undefined; }
```

Comment (BurtHarris) [inline src/Parser.ts]: Filed Microsoft/TypeScript#14487

Comment (BurtHarris) [inline src/Parser.ts]: The Typescript dev lead's note in above bug suggests they will treat this as a bug.   Updated code based on your review.
